version: '3.9'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automed-dashboard
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@10.22.26.77:27017/automedtest-dashboard
      - MONGODB_DB=automedtest-dashboard
    restart: unless-stopped